[package]
name = "portal-solutions-blitz-arm"
version = "0.1.0"
edition = "2024"
license.workspace = true
description.workspace = true

[dependencies]
portal-solutions-blitz-codegen.workspace = true
portal-solutions-blitz-common = { workspace = true, features = ["asm"] }
portal-pc-asm-common = { workspace = true }
portal-solutions-asm-arm = { workspace = true, features = ["alloc"] }
wax-core.workspace = true
wasm-encoder.workspace = true
wasmparser.workspace = true
