[package]
name = "portal-solutions-blitz-aarch64"
version = "0.1.0"
edition = "2024"
license.workspace = true
description.workspace = true

[dependencies]
portal-solutions-blitz-common = { workspace = true, features = ["asm"] }
portal-solutions-asm-aarch64 = { workspace = true }
portal-solutions-asm-regalloc.workspace = true
portal-pc-asm-common = { workspace = true }
portal-solutions-blitz-i4.workspace = true
