[package]
name = "portal-solutions-blitz-reencode"
version = "0.1.0"
edition = "2024"
license.workspace = true
description.workspace = true

[dependencies]
portal-solutions-blitz-common = { workspace = true }

wasm-encoder.workspace = true
