[package]
name = "portal-solutions-blitz-tests"
version = "0.1.0"
edition = "2024"
publish = false

[dev-dependencies]
portal-solutions-blitz-js      = { path = "../blitz-js" }
portal-solutions-blitz-c       = { path = "../blitz-c" }
portal-solutions-blitz-common  = { path = "../blitz-common" }
portal-solutions-blitz-x86-64  = { path = "../blitz-x86-64" }
portal-solutions-blitz-aarch64 = { path = "../blitz-aarch64" }
portal-solutions-blitz-riscv64 = { path = "../blitz-riscv64" }
