[package]
name = "portal-solutions-blitz-tests"
version = "0.1.0"
edition = "2024"
publish = false

[dev-dependencies]
portal-solutions-blitz-js      = { path = "../blitz-js" }
portal-solutions-blitz-c       = { path = "../blitz-c" }
portal-solutions-blitz-common  = { path = "../blitz-common" }
portal-solutions-blitz-codegen = { path = "../blitz-codegen" }
portal-solutions-blitz-x86-64  = { path = "../blitz-x86-64" }
portal-solutions-blitz-aarch64 = { path = "../blitz-aarch64" }
portal-solutions-blitz-riscv64 = { path = "../blitz-riscv64" }
portal-solutions-asm-x86-64    = { version = "0.1.0", git = "https://github.com/portal-co/asm-arch.git", features = ["iced"] }
portal-solutions-asm-aarch64   = { version = "0.1.0", git = "https://github.com/portal-co/asm-arch.git", features = ["bin-backend"] }
portal-solutions-asm-riscv64   = { version = "0.1.0", git = "https://github.com/portal-co/asm-arch.git", features = ["rv-asm-backend"] }
unicorn-engine                 = "2.1.5"
libc                           = { version = "0.2" }
paste                          = "1"
