[package]
name = "portal-solutions-blitz-ppc64"
version = "0.1.0"
edition = "2024"
license.workspace = true
description.workspace = true

[dependencies]
portal-solutions-blitz-common = { version = "0.1.0", path = "../blitz-common" }
